// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package dbsqlc

import (
	"context"
)

const countIssuesByStatus = `-- name: CountIssuesByStatus :many
SELECT status, COUNT(*) AS count FROM issues GROUP BY status
`

type CountIssuesByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountIssuesByStatus(ctx context.Context) ([]CountIssuesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countIssuesByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountIssuesByStatusRow{}
	for rows.Next() {
		var i CountIssuesByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) AS total_users FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var total_users int64
	err := row.Scan(&total_users)
	return total_users, err
}
