// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIssue = `-- name: CreateIssue :one
INSERT INTO issues (title, user_id, description, status)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, description, status, created_at, updated_at
`

type CreateIssueParams struct {
	Title       string    `json:"title"`
	UserID      uuid.UUID `json:"user_id"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.Title,
		arg.UserID,
		arg.Description,
		arg.Status,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIssue = `-- name: DeleteIssue :exec
DELETE FROM issues
WHERE id = $1
`

func (q *Queries) DeleteIssue(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteIssue, id)
	return err
}

const getIssueByID = `-- name: GetIssueByID :one
SELECT i.id, i.user_id, i.title, i.description, i.status, i.created_at, i.updated_at,
       u.name AS user_name
FROM issues i
JOIN users u ON u.id = i.user_id
WHERE i.id = $1
`

type GetIssueByIDRow struct {
	ID          int64              `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UserName    string             `json:"user_name"`
}

func (q *Queries) GetIssueByID(ctx context.Context, id int64) (GetIssueByIDRow, error) {
	row := q.db.QueryRow(ctx, getIssueByID, id)
	var i GetIssueByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
	)
	return i, err
}

const listIssues = `-- name: ListIssues :many
SELECT i.id, i.user_id, i.title, i.description, i.status, i.created_at, i.updated_at,
       u.name AS user_name
FROM issues i
JOIN users u ON u.id = i.user_id
ORDER BY i.created_at DESC
`

type ListIssuesRow struct {
	ID          int64              `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UserName    string             `json:"user_name"`
}

func (q *Queries) ListIssues(ctx context.Context) ([]ListIssuesRow, error) {
	rows, err := q.db.Query(ctx, listIssues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssuesRow{}
	for rows.Next() {
		var i ListIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesByUserID = `-- name: ListIssuesByUserID :many
SELECT i.id, i.user_id, i.title, i.description, i.status, i.created_at, i.updated_at,
       u.name AS user_name
FROM issues i
JOIN users u ON u.id = i.user_id
WHERE i.user_id = $1
ORDER BY i.created_at DESC
`

type ListIssuesByUserIDRow struct {
	ID          int64              `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UserName    string             `json:"user_name"`
}

func (q *Queries) ListIssuesByUserID(ctx context.Context, userID uuid.UUID) ([]ListIssuesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listIssuesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssuesByUserIDRow{}
	for rows.Next() {
		var i ListIssuesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssueStatus = `-- name: UpdateIssueStatus :one
UPDATE issues
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, title, description, status, created_at, updated_at
`

type UpdateIssueStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) (Issue, error) {
	row := q.db.QueryRow(ctx, updateIssueStatus, arg.ID, arg.Status)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
